### PR TITLE
Add GRQ's rest API & deployment/teardown bash scripts

### PR DESCRIPTION
**Pull request by DustinKLo**
- renamed `mozart_rest_api/` to `rest_api/`
- added grq2 rest api deployment in k8
- added 2 bash scripts (`deploy.sh` & `destroy.sh`) to make deployment and teardown of local k8 cluster a one click script
- modified `README.md` to include the grq2 rest api
- added `.gitignore`

the deployment scripts:
```bash
$ ./deploy.sh --help
Usage:
  Deploys the HySDS cluster in Kubernetes (Elasticsearch, Rest API, RabbitMQ, Redis, etc.)
  ./deploy.sh [--docker] [mozart] [grq] [--all]
  Options:
    --docker : use if running Kubernetes on Docker for Desktop; kubectl vs kubectl.docker
    --all : deploy both Mozart and GRQ cluster
    mozart : deploy Mozart cluster
    grq : deploy GRQ cluster
```

```bash
$ ./destroy.sh --help
Usage:
  Tear down the HySDS cluster in Kubernetes
  ./destroy.sh [--docker] [mozart] [grq] [--all]
  Options:
    --docker : use if running Kubernetes on Docker for Desktop; kubectl vs kubectl.docker
    --all : deploy both Mozart and GRQ cluster
    mozart : deploy mozart cluster
    grq : deploy GRQ cluster
```

the script can be ran like:
```bash
./deploy [--docker] [mozart] [grq]
```
can specify which cluster to deploy with `mozart` or `grq`, `--all` must be supplied if both arent specified
same logic applied to the `destroy.sh` script

@LucaCinquini  I'm not very good at writing bash scripts, i'm sure you have more experience so feel free to suggest any changes/improvements

### CODE REVIEW

**Review by LucaCinquini — APPROVED** [review]
Great job Dustin. I was able to use the scripts to create/destroy all resources and to publish/consume the messages.

A few suggestions:
o The README is missing the instruction to build the hysds-grq2 container
o Could you try using elasticsearch 7.16.2, which has the log4j fixes? Or is it not supported by HySDS?
o On the README, add the instructions on how to access the main GRQ URL
o Finally, perhaps the bash script could support the "--all" option to start/stop all components at once?

Thanks again.

**Comment by DustinKLo** [comment]
@LucaCinquini currently HySDS doesn't support Elasticsearch 7.10+ b/c of the AWS and Elastico conflict

Because ES moved away from an apache license (starting from v7.10) AWS can only support up to v7.9
Elastico also changed their client libraries to explicitly raise an error when connecting to a non-elastico approved elasticsearch cluster: [Source code](https://github.com/elastic/elasticsearch-py/blob/61e7a130979edd46af5ead00b03c25f71e0a2886/elasticsearch/transport.py#L412-L413)

AWS forked Elasticsearch into their own open-sourced version called OpenSearch and we'll need to do some investigation before we move in that direction

**Comment by DustinKLo** [comment]
Made the changes you recommended 👍

**Review by LucaCinquini — APPROVED** [review]
Thanks Dustin, I reviewed the last changes (without trying them) and they seem good. Please merge away...

**Pull request merged**
